spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/assessment
    username: root
    password: example
  flyway:
    locations: classpath:migrations

application:
  enable-entry-file-validation: true
  ip-api-url: "http://ip-api.com"
  ip-blocked-countries:
    - China
    - Spain
    - USA
  ip-blocked-isps:
    - AWS
    - GCP
    - Azure

